/**
 * screen names
 */
export const NavScreenTags = {
  SPLASH: 'Splash',
  INTRO: 'Intro',
  LOGIN: 'login',
  SIGN_UP: 'Signup',
  SIGN_IN: 'Signin',
  USERS: 'users',
  SCANNER: 'scanner',
  DRAWER_NAV: 'DrawerNav',
  PROFILE: 'Profile',
  WELCOME_PAGE: 'WelcomePage',
  OTP_INPUT: 'OtpInput',
  SIGN_IN_WITH_EMAIL: 'SignInWithEmail',
  FORGOT_PASSWORD: 'ForgotPassword',
  AUTH_STACK: 'AuthStack',
  SIGN_UP_WITH_EMAIL: 'SignupWithEmail',
  SIGN_UP_WITH_MOBILE: 'SignupWithMobile',
  SAFETY_ALERT: 'SafetyAlert',
  SIGNUP_SAFETY: 'SignupSafety',
  RESET_PASSWORD: 'ResetPassword',
  POST_SIGN_UP: 'PostSignUp',
  DASHBOARD_STACK: 'DashboardStack',
  DASHBOARD_HOME: 'Home',
  DASHBOARD_ORDERS: 'DashboardOrder',
  GO_TO_LOCATION: 'GoToLocation',
  VIEW_LOCATION: 'ViewLocation',
  BUNDLE_INFORMATION: 'BundleInformation',
  WALLET: 'Wallet',
  SCAN_PACKAGES: 'ScanPackages',
  VIEW_PACKAGES: 'VIEW_PACKAGES',
  TAKE_SIGNATURE: 'TAKE_SIGNATURE',
  SETTINGS: 'Settings',
  CHANGE_RADIUS: 'Change Radius',
  PROFILE_INFO: 'PROFILE_INFO',
  VERIFY_AGE: 'VERIFY_AGE',
  DELIVERED_DELIVERIES: 'Delivered Deliveries',
  WITHDRAW_REQUEST: 'Withdraw Request',
};
